
mode: "dev"  # dev开发模式
#mode: "release"  # release发布模式

app:
  name: "web_app"
  mode: "dev"
  port: 8080
  version: "v1"

# 日志
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200  # 每个日志文件大小
  max_age: 30    # 存储天数
  max_backups: 7 # 备份数量

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "admin123"
  dbname: "bluebell"
  max_open_conns: 20
  max_idle_conns: 10

redis:
  host: "10.0.3.100"
  port: 6379
  db: 8
  password: "EfcHGSzKqg6cfzWq"
  pool_size: 20